export const CLASS_COURSES = {
    "PREPA 2": [
        "Chinese Language",
        "Magnetism",
        "Humanités numériques",
        "Algorithmique – Python",
        "Probabilités 3",
        "Electronique",
        "Analysis 3",
        "Networks",
        "Gestion des Projets Créatifs",
        "Algebra 3",
        "Sciences de l'ingénieur 3",
    ],
    "MECHATRONIC 2": [
        "Embedded System",
        "Chinese Language",
        "Electricity Workshop",
        "Engineering Thermodynamics",
        "Sport",
        "Digital Electronics",
        "Electronic Workshop",
    ],
    "SOFTWARE 2": [
        "Embedded System",
        "Chinese Language",
        "Software Development Tools",
        "Analysis and Design of Information System",
        "Dynamic Web Programming and JEE",
        "Game Design and Development",
        "Object Oriented Modeling and UML",
        "Gestion des Projets Créatifs",
        "Probability and Statistic for Engineering",
    ],
    "NETWORK 2": [
        "Embedded System",
        "Chinese Language",
        "Software Development Tools",
        "Analysis and Design of Information System",
        "Dynamic Web Programming and JEE",
        "Digital Signal Processing",
        "Introduction to Cybersecurity",
        "Gestion des Projets Créatifs",
        "Probability and Statistic for Engineering",
    ],
    "SOFTWARE 3": [
        "Workshop Practice",
        "Chinese Language",
        "Software Construction and Evolution",
        "Project Management",
        "Gestion des Projets Créatifs",
        "Cloud Computing and Concepts",
        "Full Stack Web Development Technologies",
        "System Administration (Linux, Unix, Windows)",
    ],
    "CIVIL 2": [
        "Environmental Studies",
        "Chinese Language",
        "Design of Structures I",
        "Building Construction Materials II",
        "Gestion des Projets Créatifs",
        "Sport",
        "Soil Mechanics",
        "Land Surveying II",
    ],
    "CIVIL 3": [
        "Chinese Language",
        "Water Supply and Sanitation",
        "Timber and Steel Structures: Design and Construction",
        "Construction Studies Project",
        "Gestion des Projets Créatifs",
        "Sport",
        "Design Project",
        "Urban and Regional Planning and Landscape Design Planning",
    ],
    "ACCOUNTING 2": [
        "Chinese Language",
        "Corporate Governance",
        "Cost and Management Accounting",
        "Organizational Behaviour",
        "Gestion des Projets Créatifs",
        "Sport",
        "Business Law",
        "Intermediate Statistics I",
    ],
    "PROJECT MANAGEMENT 2": [
        "Chinese Language",
        "Corporate Governance",
        "Project Management Information System",
        "Organizational Behaviour",
        "Gestion des Projets Créatifs",
        "Business Project Appraisal and Selection",
        "Business Law",
        "Intermediate Statistics I",
    ],
    "BUSINESS MANAGEMENT 2": [
        "Chinese Language",
        "Principles of Corporate Law (tutorials)",
        "Cost and Management Accounting",
        "Organizational Behaviour",
        "Gestion des Projets Créatifs",
        "Sport",
        "Public Finance",
        "Intermediate Statistics I",
    ],
    "BUSINESS MANAGEMENT 3": [
        "Entrepreneurship Development (tutorials)",
        "Chinese Language",
        "Organizational Psychology",
        "Company Law",
        "Gestion des Projets Créatifs",
        "Sport",
        "Managerial Economics (Introduction to Microeconomics)",
        "Corporate Finance",
    ],
    "TOP UP PROJECT MGT": [
        "Chinese Language",
        "Corporate Governance",
        "Project Management Information System",
        "Fundamentals of Project Management",
        "Gestion des Projets Créatifs",
        "Sport",
        "Resource Mobilization and Proposal Writing",
        "Advanced Financial Accounting",
    ],
    "LEGAL CAREER 2": [
        "Commercial Law",
        "Chinese Language",
        "Labour Law",
        "Law of Evidence I",
        "Civil Procedure",
        "Sport",
        "Gestion des Projets Créatifs",
    ],
    "HEALTH SCIENCES 2": [
        "Chinese Language",
        "Microbiology/Para & Virology",
        "Applied Statistics and Computing 2 (web and its applications)",
        "Obstetric Nursing",
        "Health Assessment",
        "Nursing and Family",
        "Gestion des Projets Créatifs",
    ],
    "HEALTH SCIENCES 3": [
        "Chinese Language",
        "Professional Nursing",
        "Concept of Health and Illness Across Lifespan",
        "Applied Statistics and Computing 2 (web and its applications)",
        "Medical Surgical",
        "Gestion des Projets Créatifs",
    ],
};

export function getClassCourses(studentClass = "") {
    const normalizedClass = studentClass.trim().toUpperCase();
    const matchingClass = Object.keys(CLASS_COURSES).find(
        (className) => className.toUpperCase() === normalizedClass,
    );

    return matchingClass ? CLASS_COURSES[matchingClass] : [];
}